name: Deploy Site GH Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run graf.py
        run: python graf.py

      - name: Run analysis.py
        run: python analysis.py

      - name: Copy static files to docs folder
        run: |
          cp static/steles.css docs/
          cp static/icon/favicon.ico docs/
          cp static/script.js docs/

      - name: Copy templates files to docs folder
        run: |
          cp templates/index.html docs/

      - name: Copy generated files to docs folder
        run: |
          cp crypto_chart.html docs/
          cp analysis.txt docs/

      - name: Publish to GitHub Pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/
          git commit -m "Update site content"
          git push
